### ISSUE TITLE
server keeps crashing

### ISSUE THREAD

**Issue by AGTHARN** [Heisenburger69/BurgerSpawners#38] opened 2020-04-06 10:14 UTC
### Hi im not sure if any else has this error but this crashdump always appears when my server crashes. I would greatly appreciate if you were to help me, thanks! Heres the crashdump:

PocketMine-MP Crash Dump Mon Apr 6 09:59:27 UTC 2020

Error: Call to a member function getFolderName() on null
File: plugins/BurgerSpawners.phar/src/Heisenburger69/BurgerSpawners/EventListener
Line: 76
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: BurgerSpawners v0.0.8

Code:
[67]      */
[68]     public function onSpawn(EntitySpawnEvent $event): void
[69]     {
[70]         $entity = $event->getEntity();
[71]         $this->plugin->getScheduler()->scheduleDelayedTask(new ClosureTask(function (int $currentTick) use ($entity): void {
[72]             if (in_array($entity->getId(), $this->plugin->exemptedEntities)) return;
[73] 
[74]             $disabledWorlds = ConfigManager::getArray("mob-stacking-disabled-worlds");
[75]             if (is_array($disabledWorlds)) {
[76]                 if (in_array($entity->getLevel()->getFolderName(), $disabledWorlds)) {
[77]                     return;
[78]                 }
[79]             }
[80] 
[81]             if (ConfigManager::getToggle("allow-mob-stacking")) {
[82]                 if ($entity instanceof Human or !$entity instanceof Living) return;
[83]                 $mobStacker = new Mobstacker($entity);
[84]                 $mobStacker->stack();
[85]             }
[86]         }), 1);

**Comment by Heisenburger69** [comment] 2020-04-06 12:24
This occurs as when the server crashes, the world is unloaded and no longer exists. This should not occur when the server shuts down properly. Unless this is the reason for the crash and there are no other errors, I'm going to close the issue

**Comment by AGTHARN** [comment] 2020-04-06 13:43
Hi. Thanks for looking into the issue. I didn't quite understand that though. This crash rarely happens and occurs randomly. I'm using the Skyblock plugin but im not sure if it contributes to the crash.

**Comment by iZeaoGamer** [comment] 2020-04-06 14:24
There could be two solutions to this issue.
1. The worlds you entered in the burgerspawner config.yml, does not exist or has recently been unloaded.
2. You’ve added a Skyblock island worlds which appear to be unloaded therefore, causing the server to crash. Since I believe whenever there’s no players online on the server, then the island automatically unloads. So that could be another solution to your problem.

**Comment by iZeaoGamer** [comment] 2020-04-06 14:47
@AGTHARN The pull request should fix your issue. Please check out the Pull request so you know what we did to patch the fix. For now though, please wait until @Heisenburger69 merges it before using it so you can grab the phar file from poggit.

**Comment by Heisenburger69** [comment] 2020-04-06 14:55
This won't fix the issue since the issue is with the level being null. You need to check if the level is null, not the folder name

**Comment by iZeaoGamer** [comment] 2020-04-06 14:59
The foldername is the level name. Unless the foldername is different to the levelname, in which I would have no clue why someone would want to change the level name that’s not the folder name.

**Comment by iZeaoGamer** [comment] 2020-04-06 15:03
Okay, what about now? Check the pull request and reply there so it doesn’t overfill this issue with us talking about a pull request.

**Closed** 2020-04-06 22:10 UTC
