### ISSUE TITLE
**Reasonable Suggestion**

### ISSUE THREAD

**Issue by yxkev** [Heisenburger69/BurgerSpawners#9] opened 2020-01-29 01:26 UTC
Maybe you could make it compatible with EconomyAPI?
A feature where players can buy spawners instead of someone having to constantly give them it?
The prices would be configurable and there could be a certain permission node to help people who just want it for certain groups. =D

**Comment by Heisenburger69** [comment] 2020-01-29 07:31
Duplicate of #3

**Closed by Heisenburger69** 2020-01-29 07:31 UTC
