### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by Dapro718** [Heisenburger69/BurgerSpawners#29] opened 2020-02-17 04:24 UTC
I want to start this issue by saying, this is a awesome plugin and I am very thankful you have taken the time to create it. I also understand that you are probable being spammed with issues, so this issue isn’t that high on priority’s.

Issue:
Vanilla enchants don’t work on mobs. For example, if you have sharpness on a sword the sword still does the base damage rate.

Suggestion: 
When and if you fix this bug, maybe consider adding Custom Enchants (DaPigGuy) support.

**Comment by Johnsonk79** [comment] 2020-02-17 08:33
I don't think the problem is caused by this plugin, you need a vanilla enchantment plugin to make enchantments like sharpness work.

**Comment by Dapro718** [comment] 2020-02-17 08:35
Would teaspoon work?

**Comment by Heisenburger69** [comment] 2020-02-17 18:08
PM implements Sharpness, not sure why this issue occurs

**Comment by iZeaoGamer** [comment] 2020-02-17 18:12
Looting has been tested to work.
Not sure about sharpness though.

**Comment by iZeaoGamer** [comment] 2020-03-07 10:51
Tested sharpness, and that seems to work for me.

**Comment by Heisenburger69** [comment] 2020-03-23 17:10
Confirmed, issue only occurs for enchantments not registered by PM. Closing since it's not fixable within BurgerSpawners itself

**Closed by Heisenburger69** 2020-03-23 17:10 UTC
Labels: help wanted
