### ISSUE TITLE
BIG ISSUE :(

### ISSUE THREAD

**Issue by darkadams** [Heisenburger69/BurgerSpawners#14] opened 2020-01-31 02:01 UTC
Hi I love this plugin, but I have a issue because every time I restart the server or leave and rejoin the game my spawners went from 13 stacked spawners to 1.. pls fix this thanks.

**Comment by iZeaoGamer** [comment] 2020-01-31 03:59
I can confirm this is an issue. @Heisenburger69 you may want to find a solution to the issue.

**Comment by Heisenburger69** [comment] 2020-01-31 04:40
Duplicate of #13

**Closed by Heisenburger69** 2020-01-31 04:40 UTC
Labels: bug

**Comment by darkadams** [comment] 2020-01-31 21:24
Sorry what do u mean by duplicating? Does it mean its fixed if so what
version?

**Comment by Heisenburger69** [comment] 2020-02-01 03:59
The issue has already been reported, hence it has been marked as a duplicate. I'll be rewriting MobSpawnerTile using the EzTiles Virion by DenielWorld which supports saving Tile Data after reboots

**Comment by darkadams** [comment] 2020-02-01 04:28
Thank you so much ur the best
